-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg+eNr+uxHg39UGjpwGn1V8IrMOxZOyY99jXQeTitjSmCgCgYIKoZIzj0DAQehRANCAARfWSL4lgm2u2HAOltqOundd6ChTYKOckQl0zxXhNGI/IfQ4ywxxO+8TYt7evp7ZwUWu7G3I5QXelSWoyi6Upl2
-----END PRIVATE KEY-----